In [1]:
import numba
import numpy as np
from matplotlib import pyplot as plt

In [4]:
class Network(object):
    def __init__(self, layersizes):
        self.layersizes = layersizes
        self.network=[]
        for i in range(len(self.layersizes)-2):
            self.network.append(np.zeros([self.layersizes[i], self.layersizes[i+1]]))
            self.network.append(np.zeros([self.layersizes[i+1]]))
        self.network.append(np.zeros([self.layersizes[i+1], self.layersizes[i+2]]))
        self.network = np.array(self.network)
        


In [66]:
@numba.guvectorize([numba.void(numba.float64[:,:], numba.float64[:], numba.float64[:], numba.float64[:])],
                  '(i,o),(i),(o)->()', nopython=True)
def proplayer(weight, bias, value, res):
    res = print(np.dot(weight,value)+bias)

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.PrintConstraint object at 0x000001A221C784A8>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\typeinfer.py", line 128, in propagate
    constraint(typeinfer)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\typeinfer.py", line 600, in __call__
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1030, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\context.py", line 202, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\types\functions.py", line 49, in get_call_type
    sig = temp.apply(args, kws)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\templates.py", line 185, in apply
    sig = generic(args, kws)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\builtins.py", line 23, in generic
    raise TypeError("Type %s is not printable." % a)
TypeError: Type array(float64, 1d, C) is not printable.
--%<-----------------------------------------------------------------

File "<ipython-input-66-c95c918d3137>", line 4

In [62]:
proplayer(w,b,v)

matrix([[  3.45845952e-323]])

In [63]:
w

matrix([[1, 1, 1],
        [1, 1, 1]])

In [64]:
b

array([1, 2])

In [65]:
v

array([2, 3, 4])